### ISSUE TITLE
Aceptas colaboraciones?

### ISSUE THREAD

**Issue by RaulCatalinas** [CARLOSMARES/chat-tiempo-real#3]
Hola, me gustaría ayudar, aceptas colaboraciones? y de ser así que falta por hacer?

**Comment by CARLOSMARES** [comment]
Hola buenas tardes si acepto colaboraciones y lo que puede incorporar

**Comment by RaulCatalinas** [comment]
Que falta por hacer?

**Comment by CARLOSMARES** [comment]
Mejorar la UI
